<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gatherum.Core\Gatherum.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
  </ItemGroup>

</Project>
